# Generated by Django 5.1.2 on 2024-11-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockproduct',
            unique_together={('product', 'stock')},
        ),
    ]
